# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbdbb158933135e9bd98b3025f612d0a039784c1ea57832e6a80eaa3e57708a50c2d9828eae1e0ba2008c43e71e47a323b310d1b24352f25d73f670b6c607656

test:
  secret_key_base: 61164855a61c856624208c90a52f22d6f1d61dbf701997c5f345db5ce31f57a76cd635b53a10c4dafe822add0be9db24e7a7fd755b6093245381b1279f056e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
